# run in Linux only
version: "2.1"
volumes:
  thingsboard_data:
networks:
  thingsboard_network:
  kafka_network:
services:
  thingsboard:
    restart: unless-stopped
    image: thingsboard/tb-cassandra:${THINGSBOARD_VERSION:-3.0.1}
    depends_on:
      - kafka
    ports:
      - 9090:9090
      - 1883:1883
      - 5683:5683/udp
    environment:
      TB_QUEUE_TYPE: kafka
      TB_KAFKA_SERVERS: kafka:9092
    volumes:
      - thingsboard_data:/data
      - ./logs:/var/log/thingsboard
    networks:
      - thingsboard_network
  kafka:
    restart: unless-stopped
    image: wurstmeister/kafka:${KAFKA_VERSION:-2.12-2.5.0}
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INSIDE://:9093,OUTSIDE://:9092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9093,OUTSIDE://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes: # bind to host docker daemon
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - thingsboard_network
      - kafka_network
  zookeeper:
    restart: unless-stopped
    image: zookeeper:${ZOOKEEPER_VERSION:-3.5}
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888;zookeeper:2181
    networks:
      - kafka_network
